pipeline {
  agent any

  environment {
    APP_DIR = "/home/ubuntu/ares2-app/frontend"
    GIT_URL = "https://github.com/HarshalFulmali/ares2-app.git"
    GIT_CREDS = "7c00f801-2e76-4079-bcf8-7a53a4bbf5aa"
  }
  options { timestamps() }

  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Sync to Server Dir') {
      steps {
        sh """
          rsync -a --delete ./frontend/ ${APP_DIR}/
        """
      }
    }

    stage('Node deps') {
      steps {
        sh '''
          export NVM_DIR=/home/ubuntu/.nvm
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

            cd /home/ubuntu/ares2-app/frontend

            npm install
        '''
      }
    }

    stage('Restart Express (pm2)') {
      steps {
        sh '''
          cd /home/ubuntu/ares2-app/frontend
          pm2 restart express-app || pm2 start "npm start" --name express-app --update-env
        '''
      }
    }
  }

  post {
    success { echo 'Express deployed' }
    failure { echo 'Express deployment failed' }
  }
}
