pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install Dependencies') {
            steps {
                sh """
                python3 -m venv ${VENV} || true
                . ${VENV}/bin/activate
                pip install --upgrade pip
                pip install -r ${APP_DIR}/requirements.txt
                """
            }
        }

        stage('Deploy') {
            steps {
                sh 'pm2 restart flask-app || pm2 start "python3 app.py" --name flask-app'
            }
        }

        
        
    }
    post {
      success {
            echo 'Deployment succeeded!'
        }
        failure {
            echo 'flask app Deployment failed!'
        }      
    }
}
